# Generated by Django 5.1 on 2024-11-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveSmallIntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=100)),
                ('stock', models.PositiveSmallIntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
