# Generated by Django 5.1 on 2024-11-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0002_producto_delete_materia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
