# Generated by Django 5.1 on 2024-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0003_rename_tamaño_producto_tamano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='desc',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tamano',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
