# Generated by Django 5.1 on 2024-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_empleado', models.CharField(max_length=100)),
                ('id_cliente', models.CharField(max_length=100)),
                ('id_producto', models.CharField(max_length=100)),
                ('fecha_venta', models.CharField(max_length=100)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
