# Generated by Django 5.1 on 2024-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_cliente',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_producto',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(),
        ),
    ]
