# Generated by Django 5.1 on 2024-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0002_alter_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_inicio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pedidos',
            field=models.IntegerField(),
        ),
    ]
