# Generated by Django 5.1 on 2024-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_app', '0003_alter_cliente_celular_alter_cliente_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
