# Generated by Django 5.1 on 2024-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.PositiveSmallIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('celular', models.PositiveSmallIntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
